/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 88
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comments_token1 = 1,
  aux_sym_command_token1 = 2,
  sym_run = 3,
  sym_command_name = 4,
  aux_sym_bare_word_token1 = 5,
  sym_resource_location = 6,
  sym_operators = 7,
  sym_string = 8,
  anon_sym_AT = 9,
  aux_sym_selector_token1 = 10,
  anon_sym_LBRACK = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACK = 13,
  anon_sym_EQ = 14,
  anon_sym_BANG = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_COLON = 18,
  aux_sym_json_key_token1 = 19,
  aux_sym_number_token1 = 20,
  aux_sym_coordinates_token1 = 21,
  anon_sym_DOT_DOT = 22,
  sym_source_file = 23,
  sym_comments = 24,
  sym_command = 25,
  sym_bare_word = 26,
  sym_argument = 27,
  sym_selector = 28,
  sym_selector_argument = 29,
  sym_json_object = 30,
  sym_json_pair = 31,
  sym_json_key = 32,
  sym_json_array = 33,
  sym_number = 34,
  sym_coordinates = 35,
  sym_range = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_command_repeat1 = 38,
  aux_sym_selector_repeat1 = 39,
  aux_sym_json_object_repeat1 = 40,
  aux_sym_json_array_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comments_token1] = "comments_token1",
  [aux_sym_command_token1] = "command_token1",
  [sym_run] = "run",
  [sym_command_name] = "command_name",
  [aux_sym_bare_word_token1] = "bare_word_token1",
  [sym_resource_location] = "resource_location",
  [sym_operators] = "operators",
  [sym_string] = "string",
  [anon_sym_AT] = "@",
  [aux_sym_selector_token1] = "selector_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [aux_sym_json_key_token1] = "json_key_token1",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_coordinates_token1] = "coordinates_token1",
  [anon_sym_DOT_DOT] = "..",
  [sym_source_file] = "source_file",
  [sym_comments] = "comments",
  [sym_command] = "command",
  [sym_bare_word] = "bare_word",
  [sym_argument] = "argument",
  [sym_selector] = "selector",
  [sym_selector_argument] = "selector_argument",
  [sym_json_object] = "json_object",
  [sym_json_pair] = "json_pair",
  [sym_json_key] = "json_key",
  [sym_json_array] = "json_array",
  [sym_number] = "number",
  [sym_coordinates] = "coordinates",
  [sym_range] = "range",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_selector_repeat1] = "selector_repeat1",
  [aux_sym_json_object_repeat1] = "json_object_repeat1",
  [aux_sym_json_array_repeat1] = "json_array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comments_token1] = aux_sym_comments_token1,
  [aux_sym_command_token1] = aux_sym_command_token1,
  [sym_run] = sym_run,
  [sym_command_name] = sym_command_name,
  [aux_sym_bare_word_token1] = aux_sym_bare_word_token1,
  [sym_resource_location] = sym_resource_location,
  [sym_operators] = sym_operators,
  [sym_string] = sym_string,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_selector_token1] = aux_sym_selector_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_json_key_token1] = aux_sym_json_key_token1,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_coordinates_token1] = aux_sym_coordinates_token1,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_source_file] = sym_source_file,
  [sym_comments] = sym_comments,
  [sym_command] = sym_command,
  [sym_bare_word] = sym_bare_word,
  [sym_argument] = sym_argument,
  [sym_selector] = sym_selector,
  [sym_selector_argument] = sym_selector_argument,
  [sym_json_object] = sym_json_object,
  [sym_json_pair] = sym_json_pair,
  [sym_json_key] = sym_json_key,
  [sym_json_array] = sym_json_array,
  [sym_number] = sym_number,
  [sym_coordinates] = sym_coordinates,
  [sym_range] = sym_range,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_selector_repeat1] = aux_sym_selector_repeat1,
  [aux_sym_json_object_repeat1] = aux_sym_json_object_repeat1,
  [aux_sym_json_array_repeat1] = aux_sym_json_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comments_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_run] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_bare_word_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_resource_location] = {
    .visible = true,
    .named = true,
  },
  [sym_operators] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_selector_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_json_key_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_coordinates_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comments] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_word] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_json_object] = {
    .visible = true,
    .named = true,
  },
  [sym_json_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_json_key] = {
    .visible = true,
    .named = true,
  },
  [sym_json_array] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_coordinates] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_key = 2,
  field_name = 3,
  field_run = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_key] = "key",
  [field_name] = "name",
  [field_run] = "run",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_run, 1},
  [3] =
    {field_argument, 0},
  [4] =
    {field_argument, 1, .inherited = true},
    {field_name, 0},
  [6] =
    {field_argument, 1, .inherited = true},
    {field_name, 0},
    {field_run, 2},
  [9] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [11] =
    {field_key, 0},
    {field_value, 2},
  [13] =
    {field_key, 0},
    {field_value, 2},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 24,
  [35] = 9,
  [36] = 8,
  [37] = 7,
  [38] = 32,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 40,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 12,
  [52] = 15,
  [53] = 16,
  [54] = 54,
  [55] = 18,
  [56] = 19,
  [57] = 21,
  [58] = 22,
  [59] = 59,
  [60] = 47,
  [61] = 54,
  [62] = 50,
  [63] = 59,
  [64] = 41,
  [65] = 65,
  [66] = 14,
  [67] = 67,
  [68] = 17,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 20,
  [74] = 74,
  [75] = 25,
  [76] = 23,
  [77] = 13,
  [78] = 10,
  [79] = 79,
  [80] = 80,
  [81] = 67,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 83,
  [86] = 86,
  [87] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 40,
        '"', 6,
        '#', 10,
        ',', 37,
        '.', 8,
        ':', 43,
        '=', 39,
        '@', 34,
        '[', 36,
        ']', 38,
        '{', 41,
        '}', 42,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
        '*', 30,
        '/', 30,
        '<', 30,
        '>', 30,
        'a', 35,
        'e', 35,
        'n', 35,
        'p', 35,
        'r', 35,
        's', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        0, 20,
        '\n', 20,
        '"', 6,
        '#', 14,
        '.', 8,
        '@', 34,
        '[', 36,
        'r', 24,
        '{', 41,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 40,
        '"', 6,
        '#', 14,
        '.', 8,
        '@', 34,
        '[', 36,
        ']', 38,
        '{', 41,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
      );
      if (lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 6,
        '#', 14,
        '.', 8,
        '@', 34,
        '[', 36,
        'r', 24,
        '{', 41,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
      );
      if (lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '[') ADVANCE(36);
      if (lookahead == '{') ADVANCE(41);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '=') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comments_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comments_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_command_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_run);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_command_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_resource_location);
      if (lookahead == ':') ADVANCE(15);
      if (('/' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_resource_location);
      if (('/' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operators);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_operators);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_selector_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_json_key_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_coordinates_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 16},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 16},
  [44] = {.lex_state = 16},
  [45] = {.lex_state = 16},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 16},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 16},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 16},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 16},
  [82] = {.lex_state = 16},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comments_token1] = ACTIONS(1),
    [sym_operators] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_selector_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_coordinates_token1] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(86),
    [sym_comments] = STATE(31),
    [sym_command] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comments_token1] = ACTIONS(5),
    [sym_command_name] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(9), 1,
      aux_sym_command_token1,
    ACTIONS(11), 1,
      sym_run,
    ACTIONS(13), 1,
      aux_sym_bare_word_token1,
    ACTIONS(17), 1,
      anon_sym_AT,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      aux_sym_coordinates_token1,
    ACTIONS(27), 1,
      anon_sym_DOT_DOT,
    STATE(4), 1,
      aux_sym_command_repeat1,
    STATE(11), 1,
      sym_argument,
    STATE(12), 1,
      sym_number,
    ACTIONS(15), 3,
      sym_resource_location,
      sym_operators,
      sym_string,
    STATE(13), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [50] = 14,
    ACTIONS(13), 1,
      aux_sym_bare_word_token1,
    ACTIONS(17), 1,
      anon_sym_AT,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      aux_sym_number_token1,
    ACTIONS(25), 1,
      aux_sym_coordinates_token1,
    ACTIONS(27), 1,
      anon_sym_DOT_DOT,
    ACTIONS(29), 1,
      aux_sym_command_token1,
    ACTIONS(31), 1,
      sym_run,
    STATE(2), 1,
      aux_sym_command_repeat1,
    STATE(11), 1,
      sym_argument,
    STATE(12), 1,
      sym_number,
    ACTIONS(15), 3,
      sym_resource_location,
      sym_operators,
      sym_string,
    STATE(13), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [100] = 14,
    ACTIONS(33), 1,
      aux_sym_command_token1,
    ACTIONS(35), 1,
      sym_run,
    ACTIONS(37), 1,
      aux_sym_bare_word_token1,
    ACTIONS(43), 1,
      anon_sym_AT,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(52), 1,
      aux_sym_number_token1,
    ACTIONS(55), 1,
      aux_sym_coordinates_token1,
    ACTIONS(58), 1,
      anon_sym_DOT_DOT,
    STATE(4), 1,
      aux_sym_command_repeat1,
    STATE(11), 1,
      sym_argument,
    STATE(12), 1,
      sym_number,
    ACTIONS(40), 3,
      sym_resource_location,
      sym_operators,
      sym_string,
    STATE(13), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [150] = 13,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(65), 1,
      sym_string,
    ACTIONS(67), 1,
      anon_sym_AT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(71), 1,
      anon_sym_BANG,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(77), 1,
      aux_sym_coordinates_token1,
    ACTIONS(79), 1,
      anon_sym_DOT_DOT,
    STATE(51), 1,
      sym_number,
    STATE(70), 1,
      sym_argument,
    ACTIONS(63), 2,
      sym_resource_location,
      sym_operators,
    STATE(77), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [196] = 12,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(65), 1,
      sym_string,
    ACTIONS(67), 1,
      anon_sym_AT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(77), 1,
      aux_sym_coordinates_token1,
    ACTIONS(79), 1,
      anon_sym_DOT_DOT,
    STATE(51), 1,
      sym_number,
    STATE(74), 1,
      sym_argument,
    ACTIONS(63), 2,
      sym_resource_location,
      sym_operators,
    STATE(77), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [239] = 4,
    ACTIONS(23), 1,
      aux_sym_number_token1,
    ACTIONS(81), 1,
      aux_sym_command_token1,
    STATE(20), 1,
      sym_number,
    ACTIONS(83), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [261] = 4,
    ACTIONS(23), 1,
      aux_sym_number_token1,
    ACTIONS(85), 1,
      aux_sym_command_token1,
    STATE(14), 1,
      sym_number,
    ACTIONS(87), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [283] = 4,
    ACTIONS(23), 1,
      aux_sym_number_token1,
    ACTIONS(89), 1,
      aux_sym_command_token1,
    STATE(17), 1,
      sym_number,
    ACTIONS(91), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [305] = 2,
    ACTIONS(93), 1,
      aux_sym_command_token1,
    ACTIONS(95), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [322] = 2,
    ACTIONS(97), 1,
      aux_sym_command_token1,
    ACTIONS(99), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [339] = 3,
    ACTIONS(101), 1,
      aux_sym_command_token1,
    ACTIONS(105), 1,
      anon_sym_DOT_DOT,
    ACTIONS(103), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
  [358] = 2,
    ACTIONS(101), 1,
      aux_sym_command_token1,
    ACTIONS(103), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [375] = 2,
    ACTIONS(81), 1,
      aux_sym_command_token1,
    ACTIONS(83), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [392] = 3,
    ACTIONS(107), 1,
      aux_sym_command_token1,
    ACTIONS(111), 1,
      anon_sym_LBRACK,
    ACTIONS(109), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [411] = 2,
    ACTIONS(113), 1,
      aux_sym_command_token1,
    ACTIONS(115), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [428] = 2,
    ACTIONS(117), 1,
      aux_sym_command_token1,
    ACTIONS(119), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [445] = 2,
    ACTIONS(121), 1,
      aux_sym_command_token1,
    ACTIONS(123), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [462] = 2,
    ACTIONS(125), 1,
      aux_sym_command_token1,
    ACTIONS(127), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [479] = 2,
    ACTIONS(129), 1,
      aux_sym_command_token1,
    ACTIONS(131), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [496] = 2,
    ACTIONS(133), 1,
      aux_sym_command_token1,
    ACTIONS(135), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [513] = 2,
    ACTIONS(137), 1,
      aux_sym_command_token1,
    ACTIONS(139), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [530] = 2,
    ACTIONS(141), 1,
      aux_sym_command_token1,
    ACTIONS(143), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [547] = 2,
    ACTIONS(145), 1,
      aux_sym_command_token1,
    ACTIONS(147), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [564] = 2,
    ACTIONS(149), 1,
      aux_sym_command_token1,
    ACTIONS(151), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [581] = 8,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(153), 1,
      sym_resource_location,
    ACTIONS(155), 1,
      sym_string,
    ACTIONS(157), 1,
      anon_sym_RBRACK,
    STATE(47), 4,
      sym_bare_word,
      sym_json_object,
      sym_json_array,
      sym_number,
  [609] = 8,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(159), 1,
      sym_resource_location,
    ACTIONS(161), 1,
      sym_string,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    STATE(60), 4,
      sym_bare_word,
      sym_json_object,
      sym_json_array,
      sym_number,
  [637] = 7,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(165), 1,
      sym_resource_location,
    ACTIONS(167), 1,
      sym_string,
    STATE(72), 4,
      sym_bare_word,
      sym_json_object,
      sym_json_array,
      sym_number,
  [662] = 5,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(169), 2,
      sym_resource_location,
      sym_string,
    STATE(69), 3,
      sym_json_object,
      sym_json_array,
      sym_number,
  [681] = 4,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 1,
      aux_sym_comments_token1,
    ACTIONS(176), 1,
      sym_command_name,
    STATE(30), 3,
      sym_comments,
      sym_command,
      aux_sym_source_file_repeat1,
  [696] = 4,
    ACTIONS(5), 1,
      aux_sym_comments_token1,
    ACTIONS(7), 1,
      sym_command_name,
    ACTIONS(179), 1,
      ts_builtin_sym_end,
    STATE(30), 3,
      sym_comments,
      sym_command,
      aux_sym_source_file_repeat1,
  [711] = 3,
    STATE(54), 1,
      sym_json_pair,
    STATE(87), 1,
      sym_json_key,
    ACTIONS(181), 2,
      sym_string,
      aux_sym_json_key_token1,
  [722] = 3,
    STATE(80), 1,
      sym_json_pair,
    STATE(87), 1,
      sym_json_key,
    ACTIONS(181), 2,
      sym_string,
      aux_sym_json_key_token1,
  [733] = 1,
    ACTIONS(145), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [740] = 3,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    STATE(68), 1,
      sym_number,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [751] = 3,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    STATE(66), 1,
      sym_number,
    ACTIONS(85), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [762] = 3,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    STATE(73), 1,
      sym_number,
    ACTIONS(81), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [773] = 3,
    STATE(61), 1,
      sym_json_pair,
    STATE(87), 1,
      sym_json_key,
    ACTIONS(181), 2,
      sym_string,
      aux_sym_json_key_token1,
  [784] = 3,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_json_object_repeat1,
  [794] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(190), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      aux_sym_selector_repeat1,
  [804] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(192), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      aux_sym_selector_repeat1,
  [814] = 3,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_json_array_repeat1,
  [824] = 1,
    ACTIONS(199), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [830] = 1,
    ACTIONS(201), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [836] = 1,
    ACTIONS(203), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [842] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      aux_sym_selector_repeat1,
  [852] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(209), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_json_array_repeat1,
  [862] = 3,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    ACTIONS(214), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      aux_sym_selector_repeat1,
  [872] = 1,
    ACTIONS(216), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [878] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_json_array_repeat1,
  [888] = 2,
    ACTIONS(220), 1,
      anon_sym_DOT_DOT,
    ACTIONS(101), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [896] = 2,
    ACTIONS(222), 1,
      anon_sym_LBRACK,
    ACTIONS(107), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [904] = 1,
    ACTIONS(113), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [910] = 3,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      aux_sym_json_object_repeat1,
  [920] = 1,
    ACTIONS(121), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [926] = 1,
    ACTIONS(125), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [932] = 1,
    ACTIONS(133), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [938] = 1,
    ACTIONS(137), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [944] = 3,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_json_object_repeat1,
  [954] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      aux_sym_json_array_repeat1,
  [964] = 3,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    STATE(63), 1,
      aux_sym_json_object_repeat1,
  [974] = 3,
    ACTIONS(207), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_json_array_repeat1,
  [984] = 3,
    ACTIONS(224), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_json_object_repeat1,
  [994] = 3,
    ACTIONS(188), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACK,
    STATE(40), 1,
      aux_sym_selector_repeat1,
  [1004] = 1,
    ACTIONS(240), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [1010] = 1,
    ACTIONS(81), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1015] = 2,
    ACTIONS(242), 1,
      sym_command_name,
    STATE(41), 1,
      sym_selector_argument,
  [1022] = 1,
    ACTIONS(117), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1027] = 1,
    ACTIONS(244), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1032] = 1,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1037] = 1,
    ACTIONS(214), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1042] = 1,
    ACTIONS(197), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1047] = 1,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1052] = 1,
    ACTIONS(248), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1057] = 1,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1062] = 1,
    ACTIONS(141), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1067] = 1,
    ACTIONS(101), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1072] = 1,
    ACTIONS(93), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1077] = 2,
    ACTIONS(242), 1,
      sym_command_name,
    STATE(71), 1,
      sym_selector_argument,
  [1084] = 1,
    ACTIONS(186), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1089] = 2,
    ACTIONS(242), 1,
      sym_command_name,
    STATE(64), 1,
      sym_selector_argument,
  [1096] = 1,
    ACTIONS(250), 1,
      anon_sym_EQ,
  [1100] = 1,
    ACTIONS(252), 1,
      aux_sym_selector_token1,
  [1104] = 1,
    ACTIONS(254), 1,
      anon_sym_COLON,
  [1108] = 1,
    ACTIONS(256), 1,
      aux_sym_selector_token1,
  [1112] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [1116] = 1,
    ACTIONS(260), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 239,
  [SMALL_STATE(8)] = 261,
  [SMALL_STATE(9)] = 283,
  [SMALL_STATE(10)] = 305,
  [SMALL_STATE(11)] = 322,
  [SMALL_STATE(12)] = 339,
  [SMALL_STATE(13)] = 358,
  [SMALL_STATE(14)] = 375,
  [SMALL_STATE(15)] = 392,
  [SMALL_STATE(16)] = 411,
  [SMALL_STATE(17)] = 428,
  [SMALL_STATE(18)] = 445,
  [SMALL_STATE(19)] = 462,
  [SMALL_STATE(20)] = 479,
  [SMALL_STATE(21)] = 496,
  [SMALL_STATE(22)] = 513,
  [SMALL_STATE(23)] = 530,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 564,
  [SMALL_STATE(26)] = 581,
  [SMALL_STATE(27)] = 609,
  [SMALL_STATE(28)] = 637,
  [SMALL_STATE(29)] = 662,
  [SMALL_STATE(30)] = 681,
  [SMALL_STATE(31)] = 696,
  [SMALL_STATE(32)] = 711,
  [SMALL_STATE(33)] = 722,
  [SMALL_STATE(34)] = 733,
  [SMALL_STATE(35)] = 740,
  [SMALL_STATE(36)] = 751,
  [SMALL_STATE(37)] = 762,
  [SMALL_STATE(38)] = 773,
  [SMALL_STATE(39)] = 784,
  [SMALL_STATE(40)] = 794,
  [SMALL_STATE(41)] = 804,
  [SMALL_STATE(42)] = 814,
  [SMALL_STATE(43)] = 824,
  [SMALL_STATE(44)] = 830,
  [SMALL_STATE(45)] = 836,
  [SMALL_STATE(46)] = 842,
  [SMALL_STATE(47)] = 852,
  [SMALL_STATE(48)] = 862,
  [SMALL_STATE(49)] = 872,
  [SMALL_STATE(50)] = 878,
  [SMALL_STATE(51)] = 888,
  [SMALL_STATE(52)] = 896,
  [SMALL_STATE(53)] = 904,
  [SMALL_STATE(54)] = 910,
  [SMALL_STATE(55)] = 920,
  [SMALL_STATE(56)] = 926,
  [SMALL_STATE(57)] = 932,
  [SMALL_STATE(58)] = 938,
  [SMALL_STATE(59)] = 944,
  [SMALL_STATE(60)] = 954,
  [SMALL_STATE(61)] = 964,
  [SMALL_STATE(62)] = 974,
  [SMALL_STATE(63)] = 984,
  [SMALL_STATE(64)] = 994,
  [SMALL_STATE(65)] = 1004,
  [SMALL_STATE(66)] = 1010,
  [SMALL_STATE(67)] = 1015,
  [SMALL_STATE(68)] = 1022,
  [SMALL_STATE(69)] = 1027,
  [SMALL_STATE(70)] = 1032,
  [SMALL_STATE(71)] = 1037,
  [SMALL_STATE(72)] = 1042,
  [SMALL_STATE(73)] = 1047,
  [SMALL_STATE(74)] = 1052,
  [SMALL_STATE(75)] = 1057,
  [SMALL_STATE(76)] = 1062,
  [SMALL_STATE(77)] = 1067,
  [SMALL_STATE(78)] = 1072,
  [SMALL_STATE(79)] = 1077,
  [SMALL_STATE(80)] = 1084,
  [SMALL_STATE(81)] = 1089,
  [SMALL_STATE(82)] = 1096,
  [SMALL_STATE(83)] = 1100,
  [SMALL_STATE(84)] = 1104,
  [SMALL_STATE(85)] = 1108,
  [SMALL_STATE(86)] = 1112,
  [SMALL_STATE(87)] = 1116,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(13),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(85),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(26),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(32),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(24),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(9),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(8),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coordinates, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_coordinates, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_word, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bare_word, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1, 0, 3),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1, 0, 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 2, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coordinates, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_coordinates, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 6, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 6, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [194] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comments, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 5),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_pair, 3, 0, 7),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_argument, 3, 0, 7),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_argument, 4, 0, 8),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_key, 1, 0, 0),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [258] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mcfunction(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mcfunction",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
