/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comments_token1 = 1,
  aux_sym_command_token1 = 2,
  sym_run = 3,
  sym_command_name = 4,
  sym_bare_word = 5,
  sym_resource_location = 6,
  sym_string = 7,
  anon_sym_AT = 8,
  aux_sym_selector_token1 = 9,
  anon_sym_LBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_RBRACK = 12,
  anon_sym_EQ = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_COLON = 16,
  aux_sym_json_key_token1 = 17,
  sym_number = 18,
  aux_sym_coordinates_token1 = 19,
  anon_sym_DOT_DOT = 20,
  sym_source_file = 21,
  sym_comments = 22,
  sym_command = 23,
  sym_argument = 24,
  sym_selector = 25,
  sym_selector_argument = 26,
  sym_json_object = 27,
  sym_json_pair = 28,
  sym_json_key = 29,
  sym_json_array = 30,
  sym_coordinates = 31,
  sym_range = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_command_repeat1 = 34,
  aux_sym_selector_repeat1 = 35,
  aux_sym_json_object_repeat1 = 36,
  aux_sym_json_array_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comments_token1] = "comments_token1",
  [aux_sym_command_token1] = "command_token1",
  [sym_run] = "run",
  [sym_command_name] = "command_name",
  [sym_bare_word] = "bare_word",
  [sym_resource_location] = "resource_location",
  [sym_string] = "string",
  [anon_sym_AT] = "@",
  [aux_sym_selector_token1] = "selector_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [aux_sym_json_key_token1] = "json_key_token1",
  [sym_number] = "number",
  [aux_sym_coordinates_token1] = "coordinates_token1",
  [anon_sym_DOT_DOT] = "..",
  [sym_source_file] = "source_file",
  [sym_comments] = "comments",
  [sym_command] = "command",
  [sym_argument] = "argument",
  [sym_selector] = "selector",
  [sym_selector_argument] = "selector_argument",
  [sym_json_object] = "json_object",
  [sym_json_pair] = "json_pair",
  [sym_json_key] = "json_key",
  [sym_json_array] = "json_array",
  [sym_coordinates] = "coordinates",
  [sym_range] = "range",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_selector_repeat1] = "selector_repeat1",
  [aux_sym_json_object_repeat1] = "json_object_repeat1",
  [aux_sym_json_array_repeat1] = "json_array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comments_token1] = aux_sym_comments_token1,
  [aux_sym_command_token1] = aux_sym_command_token1,
  [sym_run] = sym_run,
  [sym_command_name] = sym_command_name,
  [sym_bare_word] = sym_bare_word,
  [sym_resource_location] = sym_resource_location,
  [sym_string] = sym_string,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_selector_token1] = aux_sym_selector_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_json_key_token1] = aux_sym_json_key_token1,
  [sym_number] = sym_number,
  [aux_sym_coordinates_token1] = aux_sym_coordinates_token1,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_source_file] = sym_source_file,
  [sym_comments] = sym_comments,
  [sym_command] = sym_command,
  [sym_argument] = sym_argument,
  [sym_selector] = sym_selector,
  [sym_selector_argument] = sym_selector_argument,
  [sym_json_object] = sym_json_object,
  [sym_json_pair] = sym_json_pair,
  [sym_json_key] = sym_json_key,
  [sym_json_array] = sym_json_array,
  [sym_coordinates] = sym_coordinates,
  [sym_range] = sym_range,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_selector_repeat1] = aux_sym_selector_repeat1,
  [aux_sym_json_object_repeat1] = aux_sym_json_object_repeat1,
  [aux_sym_json_array_repeat1] = aux_sym_json_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comments_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_run] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_word] = {
    .visible = true,
    .named = true,
  },
  [sym_resource_location] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_selector_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_json_key_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_coordinates_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comments] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_json_object] = {
    .visible = true,
    .named = true,
  },
  [sym_json_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_json_key] = {
    .visible = true,
    .named = true,
  },
  [sym_json_array] = {
    .visible = true,
    .named = true,
  },
  [sym_coordinates] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_key = 2,
  field_name = 3,
  field_run = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_key] = "key",
  [field_name] = "name",
  [field_run] = "run",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_run, 1},
  [3] =
    {field_argument, 0},
  [4] =
    {field_argument, 1, .inherited = true},
    {field_name, 0},
  [6] =
    {field_argument, 1, .inherited = true},
    {field_name, 0},
    {field_run, 2},
  [9] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [11] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 28,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 8,
  [45] = 7,
  [46] = 10,
  [47] = 11,
  [48] = 12,
  [49] = 15,
  [50] = 14,
  [51] = 18,
  [52] = 20,
  [53] = 53,
  [54] = 33,
  [55] = 32,
  [56] = 34,
  [57] = 36,
  [58] = 42,
  [59] = 53,
  [60] = 9,
  [61] = 61,
  [62] = 16,
  [63] = 13,
  [64] = 64,
  [65] = 17,
  [66] = 19,
  [67] = 67,
  [68] = 21,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 70,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 79,
  [80] = 80,
  [81] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '"', 6,
        '#', 10,
        ',', 41,
        '.', 8,
        ':', 46,
        '=', 43,
        '@', 38,
        '[', 40,
        ']', 42,
        '{', 44,
        '}', 45,
        '+', 9,
        '-', 9,
        '^', 51,
        '~', 51,
        'a', 39,
        'e', 39,
        'n', 39,
        'p', 39,
        'r', 39,
        's', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '\n', 20,
        '"', 6,
        '#', 14,
        '+', 9,
        '-', 24,
        '.', 8,
        '@', 38,
        '[', 40,
        'r', 27,
        '{', 44,
        '^', 51,
        '~', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '"', 6,
        '#', 14,
        '+', 9,
        '-', 24,
        '.', 8,
        '@', 38,
        '[', 40,
        ']', 42,
        '{', 44,
        '^', 51,
        '~', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 6,
        '#', 14,
        '+', 9,
        '-', 24,
        '.', 8,
        '@', 38,
        '[', 40,
        'r', 27,
        '{', 44,
        '^', 51,
        '~', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '#') ADVANCE(14);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '[') ADVANCE(40);
      if (lookahead == '{') ADVANCE(44);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 14:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comments_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comments_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_command_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_run);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_command_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '+') ADVANCE(13);
      if (lookahead == '-') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '.') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '.') ADVANCE(30);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '/') ADVANCE(35);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_bare_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_bare_word);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_bare_word);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_resource_location);
      if (lookahead == ':') ADVANCE(15);
      if (('/' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_resource_location);
      if (('/' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_selector_token1);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_json_key_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(49);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_coordinates_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 16},
  [27] = {.lex_state = 16},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 16},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 16},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 16},
  [41] = {.lex_state = 16},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 16},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 16},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 16},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comments_token1] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_selector_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_coordinates_token1] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(74),
    [sym_comments] = STATE(26),
    [sym_command] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comments_token1] = ACTIONS(5),
    [sym_command_name] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(9), 1,
      aux_sym_command_token1,
    ACTIONS(11), 1,
      sym_run,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_coordinates_token1,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    STATE(3), 1,
      aux_sym_command_repeat1,
    STATE(6), 1,
      sym_argument,
    ACTIONS(13), 3,
      sym_bare_word,
      sym_resource_location,
      sym_string,
    STATE(9), 5,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [43] = 12,
    ACTIONS(15), 1,
      anon_sym_AT,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(21), 1,
      sym_number,
    ACTIONS(23), 1,
      aux_sym_coordinates_token1,
    ACTIONS(25), 1,
      anon_sym_DOT_DOT,
    ACTIONS(27), 1,
      aux_sym_command_token1,
    ACTIONS(29), 1,
      sym_run,
    STATE(4), 1,
      aux_sym_command_repeat1,
    STATE(6), 1,
      sym_argument,
    ACTIONS(13), 3,
      sym_bare_word,
      sym_resource_location,
      sym_string,
    STATE(9), 5,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [86] = 12,
    ACTIONS(31), 1,
      aux_sym_command_token1,
    ACTIONS(33), 1,
      sym_run,
    ACTIONS(38), 1,
      anon_sym_AT,
    ACTIONS(41), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      sym_number,
    ACTIONS(50), 1,
      aux_sym_coordinates_token1,
    ACTIONS(53), 1,
      anon_sym_DOT_DOT,
    STATE(4), 1,
      aux_sym_command_repeat1,
    STATE(6), 1,
      sym_argument,
    ACTIONS(35), 3,
      sym_bare_word,
      sym_resource_location,
      sym_string,
    STATE(9), 5,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [129] = 10,
    ACTIONS(58), 1,
      sym_string,
    ACTIONS(60), 1,
      anon_sym_AT,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      sym_number,
    ACTIONS(68), 1,
      aux_sym_coordinates_token1,
    ACTIONS(70), 1,
      anon_sym_DOT_DOT,
    STATE(64), 1,
      sym_argument,
    ACTIONS(56), 2,
      sym_bare_word,
      sym_resource_location,
    STATE(60), 5,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [165] = 2,
    ACTIONS(72), 1,
      aux_sym_command_token1,
    ACTIONS(74), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [181] = 3,
    ACTIONS(76), 1,
      aux_sym_command_token1,
    ACTIONS(80), 1,
      sym_number,
    ACTIONS(78), 9,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [199] = 3,
    ACTIONS(82), 1,
      aux_sym_command_token1,
    ACTIONS(86), 1,
      anon_sym_DOT_DOT,
    ACTIONS(84), 9,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
  [217] = 2,
    ACTIONS(82), 1,
      aux_sym_command_token1,
    ACTIONS(84), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [233] = 3,
    ACTIONS(88), 1,
      aux_sym_command_token1,
    ACTIONS(92), 1,
      anon_sym_LBRACK,
    ACTIONS(90), 9,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [251] = 2,
    ACTIONS(94), 1,
      aux_sym_command_token1,
    ACTIONS(96), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [267] = 3,
    ACTIONS(98), 1,
      aux_sym_command_token1,
    ACTIONS(102), 1,
      sym_number,
    ACTIONS(100), 9,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [285] = 2,
    ACTIONS(98), 1,
      aux_sym_command_token1,
    ACTIONS(100), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [301] = 2,
    ACTIONS(104), 1,
      aux_sym_command_token1,
    ACTIONS(106), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [317] = 2,
    ACTIONS(108), 1,
      aux_sym_command_token1,
    ACTIONS(110), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [333] = 2,
    ACTIONS(112), 1,
      aux_sym_command_token1,
    ACTIONS(114), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [349] = 2,
    ACTIONS(116), 1,
      aux_sym_command_token1,
    ACTIONS(118), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [365] = 2,
    ACTIONS(120), 1,
      aux_sym_command_token1,
    ACTIONS(122), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [381] = 2,
    ACTIONS(124), 1,
      aux_sym_command_token1,
    ACTIONS(126), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [397] = 2,
    ACTIONS(128), 1,
      aux_sym_command_token1,
    ACTIONS(130), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [413] = 2,
    ACTIONS(132), 1,
      aux_sym_command_token1,
    ACTIONS(134), 10,
      sym_run,
      sym_bare_word,
      sym_resource_location,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_number,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [429] = 6,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      sym_string,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    STATE(59), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(136), 3,
      sym_bare_word,
      sym_resource_location,
      sym_number,
  [451] = 6,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(144), 1,
      sym_string,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(53), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(142), 3,
      sym_bare_word,
      sym_resource_location,
      sym_number,
  [473] = 5,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    ACTIONS(150), 1,
      sym_string,
    STATE(72), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(148), 3,
      sym_bare_word,
      sym_resource_location,
      sym_number,
  [492] = 4,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_LBRACE,
    STATE(71), 2,
      sym_json_object,
      sym_json_array,
    ACTIONS(152), 3,
      sym_resource_location,
      sym_string,
      sym_number,
  [508] = 4,
    ACTIONS(5), 1,
      aux_sym_comments_token1,
    ACTIONS(7), 1,
      sym_command_name,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    STATE(27), 3,
      sym_comments,
      sym_command,
      aux_sym_source_file_repeat1,
  [523] = 4,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      aux_sym_comments_token1,
    ACTIONS(161), 1,
      sym_command_name,
    STATE(27), 3,
      sym_comments,
      sym_command,
      aux_sym_source_file_repeat1,
  [538] = 3,
    STATE(33), 1,
      sym_json_pair,
    STATE(80), 1,
      sym_json_key,
    ACTIONS(164), 2,
      sym_string,
      aux_sym_json_key_token1,
  [549] = 3,
    STATE(69), 1,
      sym_json_pair,
    STATE(80), 1,
      sym_json_key,
    ACTIONS(164), 2,
      sym_string,
      aux_sym_json_key_token1,
  [560] = 3,
    STATE(54), 1,
      sym_json_pair,
    STATE(80), 1,
      sym_json_key,
    ACTIONS(164), 2,
      sym_string,
      aux_sym_json_key_token1,
  [571] = 1,
    ACTIONS(166), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [577] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      aux_sym_json_array_repeat1,
  [587] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(174), 1,
      anon_sym_RBRACE,
    STATE(34), 1,
      aux_sym_json_object_repeat1,
  [597] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_json_object_repeat1,
  [607] = 1,
    ACTIONS(178), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [613] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(182), 1,
      anon_sym_RBRACK,
    STATE(42), 1,
      aux_sym_selector_repeat1,
  [623] = 3,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      aux_sym_json_array_repeat1,
  [633] = 1,
    ACTIONS(189), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [639] = 3,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_json_object_repeat1,
  [649] = 1,
    ACTIONS(196), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [655] = 1,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [661] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_selector_repeat1,
  [671] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_selector_repeat1,
  [681] = 2,
    ACTIONS(207), 1,
      anon_sym_DOT_DOT,
    ACTIONS(82), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [689] = 2,
    ACTIONS(209), 1,
      sym_number,
    ACTIONS(76), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [697] = 2,
    ACTIONS(211), 1,
      anon_sym_LBRACK,
    ACTIONS(88), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [705] = 1,
    ACTIONS(94), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [711] = 2,
    ACTIONS(213), 1,
      sym_number,
    ACTIONS(98), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [719] = 1,
    ACTIONS(108), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [725] = 1,
    ACTIONS(104), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [731] = 1,
    ACTIONS(120), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [737] = 1,
    ACTIONS(128), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [743] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(55), 1,
      aux_sym_json_array_repeat1,
  [753] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RBRACE,
    STATE(56), 1,
      aux_sym_json_object_repeat1,
  [763] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(37), 1,
      aux_sym_json_array_repeat1,
  [773] = 3,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
    STATE(39), 1,
      aux_sym_json_object_repeat1,
  [783] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(223), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      aux_sym_selector_repeat1,
  [793] = 3,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RBRACK,
    STATE(43), 1,
      aux_sym_selector_repeat1,
  [803] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
    STATE(32), 1,
      aux_sym_json_array_repeat1,
  [813] = 1,
    ACTIONS(82), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [818] = 2,
    ACTIONS(229), 1,
      sym_command_name,
    STATE(67), 1,
      sym_selector_argument,
  [825] = 1,
    ACTIONS(112), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [830] = 1,
    ACTIONS(98), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [835] = 1,
    ACTIONS(231), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [840] = 1,
    ACTIONS(116), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [845] = 1,
    ACTIONS(124), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [850] = 1,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [855] = 1,
    ACTIONS(132), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [860] = 1,
    ACTIONS(194), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [865] = 2,
    ACTIONS(229), 1,
      sym_command_name,
    STATE(36), 1,
      sym_selector_argument,
  [872] = 1,
    ACTIONS(233), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [877] = 1,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [882] = 2,
    ACTIONS(229), 1,
      sym_command_name,
    STATE(57), 1,
      sym_selector_argument,
  [889] = 1,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
  [893] = 1,
    ACTIONS(237), 1,
      anon_sym_COLON,
  [897] = 1,
    ACTIONS(239), 1,
      aux_sym_selector_token1,
  [901] = 1,
    ACTIONS(241), 1,
      sym_number,
  [905] = 1,
    ACTIONS(243), 1,
      aux_sym_selector_token1,
  [909] = 1,
    ACTIONS(245), 1,
      anon_sym_EQ,
  [913] = 1,
    ACTIONS(247), 1,
      anon_sym_COLON,
  [917] = 1,
    ACTIONS(249), 1,
      sym_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 86,
  [SMALL_STATE(5)] = 129,
  [SMALL_STATE(6)] = 165,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 199,
  [SMALL_STATE(9)] = 217,
  [SMALL_STATE(10)] = 233,
  [SMALL_STATE(11)] = 251,
  [SMALL_STATE(12)] = 267,
  [SMALL_STATE(13)] = 285,
  [SMALL_STATE(14)] = 301,
  [SMALL_STATE(15)] = 317,
  [SMALL_STATE(16)] = 333,
  [SMALL_STATE(17)] = 349,
  [SMALL_STATE(18)] = 365,
  [SMALL_STATE(19)] = 381,
  [SMALL_STATE(20)] = 397,
  [SMALL_STATE(21)] = 413,
  [SMALL_STATE(22)] = 429,
  [SMALL_STATE(23)] = 451,
  [SMALL_STATE(24)] = 473,
  [SMALL_STATE(25)] = 492,
  [SMALL_STATE(26)] = 508,
  [SMALL_STATE(27)] = 523,
  [SMALL_STATE(28)] = 538,
  [SMALL_STATE(29)] = 549,
  [SMALL_STATE(30)] = 560,
  [SMALL_STATE(31)] = 571,
  [SMALL_STATE(32)] = 577,
  [SMALL_STATE(33)] = 587,
  [SMALL_STATE(34)] = 597,
  [SMALL_STATE(35)] = 607,
  [SMALL_STATE(36)] = 613,
  [SMALL_STATE(37)] = 623,
  [SMALL_STATE(38)] = 633,
  [SMALL_STATE(39)] = 639,
  [SMALL_STATE(40)] = 649,
  [SMALL_STATE(41)] = 655,
  [SMALL_STATE(42)] = 661,
  [SMALL_STATE(43)] = 671,
  [SMALL_STATE(44)] = 681,
  [SMALL_STATE(45)] = 689,
  [SMALL_STATE(46)] = 697,
  [SMALL_STATE(47)] = 705,
  [SMALL_STATE(48)] = 711,
  [SMALL_STATE(49)] = 719,
  [SMALL_STATE(50)] = 725,
  [SMALL_STATE(51)] = 731,
  [SMALL_STATE(52)] = 737,
  [SMALL_STATE(53)] = 743,
  [SMALL_STATE(54)] = 753,
  [SMALL_STATE(55)] = 763,
  [SMALL_STATE(56)] = 773,
  [SMALL_STATE(57)] = 783,
  [SMALL_STATE(58)] = 793,
  [SMALL_STATE(59)] = 803,
  [SMALL_STATE(60)] = 813,
  [SMALL_STATE(61)] = 818,
  [SMALL_STATE(62)] = 825,
  [SMALL_STATE(63)] = 830,
  [SMALL_STATE(64)] = 835,
  [SMALL_STATE(65)] = 840,
  [SMALL_STATE(66)] = 845,
  [SMALL_STATE(67)] = 850,
  [SMALL_STATE(68)] = 855,
  [SMALL_STATE(69)] = 860,
  [SMALL_STATE(70)] = 865,
  [SMALL_STATE(71)] = 872,
  [SMALL_STATE(72)] = 877,
  [SMALL_STATE(73)] = 882,
  [SMALL_STATE(74)] = 889,
  [SMALL_STATE(75)] = 893,
  [SMALL_STATE(76)] = 897,
  [SMALL_STATE(77)] = 901,
  [SMALL_STATE(78)] = 905,
  [SMALL_STATE(79)] = 909,
  [SMALL_STATE(80)] = 913,
  [SMALL_STATE(81)] = 917,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(9),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(78),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(22),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(28),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(8),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(81),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(7),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1, 0, 3),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coordinates, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_coordinates, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 5, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 6, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 6, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [184] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comments, 1, 0, 0),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 4),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 5),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_argument, 3, 0, 7),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_pair, 3, 0, 7),
  [235] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_key, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mcfunction(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mcfunction",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
