/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_comments_token1 = 1,
  aux_sym_command_token1 = 2,
  sym_run = 3,
  sym_command_name = 4,
  aux_sym_bare_word_token1 = 5,
  sym_resource_location = 6,
  sym_operators = 7,
  sym_string = 8,
  anon_sym_AT = 9,
  aux_sym_selector_token1 = 10,
  anon_sym_LBRACK = 11,
  anon_sym_COMMA = 12,
  anon_sym_RBRACK = 13,
  anon_sym_EQ = 14,
  anon_sym_BANG = 15,
  anon_sym_LBRACE = 16,
  anon_sym_RBRACE = 17,
  anon_sym_COLON = 18,
  aux_sym_json_key_token1 = 19,
  aux_sym_number_token1 = 20,
  aux_sym_coordinates_token1 = 21,
  anon_sym_DOT_DOT = 22,
  sym_source_file = 23,
  sym_comments = 24,
  sym_command = 25,
  sym_bare_word = 26,
  sym_argument = 27,
  sym_selector = 28,
  sym_selector_argument = 29,
  sym_json_object = 30,
  sym_json_pair = 31,
  sym_json_key = 32,
  sym_json_array = 33,
  sym_number = 34,
  sym_coordinates = 35,
  sym_range = 36,
  aux_sym_source_file_repeat1 = 37,
  aux_sym_command_repeat1 = 38,
  aux_sym_selector_repeat1 = 39,
  aux_sym_json_object_repeat1 = 40,
  aux_sym_json_array_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_comments_token1] = "comments_token1",
  [aux_sym_command_token1] = "command_token1",
  [sym_run] = "run",
  [sym_command_name] = "command_name",
  [aux_sym_bare_word_token1] = "bare_word_token1",
  [sym_resource_location] = "resource_location",
  [sym_operators] = "operators",
  [sym_string] = "string",
  [anon_sym_AT] = "@",
  [aux_sym_selector_token1] = "selector_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG] = "!",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [aux_sym_json_key_token1] = "json_key_token1",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_coordinates_token1] = "coordinates_token1",
  [anon_sym_DOT_DOT] = "..",
  [sym_source_file] = "source_file",
  [sym_comments] = "comments",
  [sym_command] = "command",
  [sym_bare_word] = "bare_word",
  [sym_argument] = "argument",
  [sym_selector] = "selector",
  [sym_selector_argument] = "selector_argument",
  [sym_json_object] = "json_object",
  [sym_json_pair] = "json_pair",
  [sym_json_key] = "json_key",
  [sym_json_array] = "json_array",
  [sym_number] = "number",
  [sym_coordinates] = "coordinates",
  [sym_range] = "range",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_selector_repeat1] = "selector_repeat1",
  [aux_sym_json_object_repeat1] = "json_object_repeat1",
  [aux_sym_json_array_repeat1] = "json_array_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_comments_token1] = aux_sym_comments_token1,
  [aux_sym_command_token1] = aux_sym_command_token1,
  [sym_run] = sym_run,
  [sym_command_name] = sym_command_name,
  [aux_sym_bare_word_token1] = aux_sym_bare_word_token1,
  [sym_resource_location] = sym_resource_location,
  [sym_operators] = sym_operators,
  [sym_string] = sym_string,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_selector_token1] = aux_sym_selector_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_json_key_token1] = aux_sym_json_key_token1,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_coordinates_token1] = aux_sym_coordinates_token1,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [sym_source_file] = sym_source_file,
  [sym_comments] = sym_comments,
  [sym_command] = sym_command,
  [sym_bare_word] = sym_bare_word,
  [sym_argument] = sym_argument,
  [sym_selector] = sym_selector,
  [sym_selector_argument] = sym_selector_argument,
  [sym_json_object] = sym_json_object,
  [sym_json_pair] = sym_json_pair,
  [sym_json_key] = sym_json_key,
  [sym_json_array] = sym_json_array,
  [sym_number] = sym_number,
  [sym_coordinates] = sym_coordinates,
  [sym_range] = sym_range,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_selector_repeat1] = aux_sym_selector_repeat1,
  [aux_sym_json_object_repeat1] = aux_sym_json_object_repeat1,
  [aux_sym_json_array_repeat1] = aux_sym_json_array_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_comments_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_run] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_bare_word_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_resource_location] = {
    .visible = true,
    .named = true,
  },
  [sym_operators] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_selector_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_json_key_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_coordinates_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comments] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_bare_word] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_selector_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_json_object] = {
    .visible = true,
    .named = true,
  },
  [sym_json_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_json_key] = {
    .visible = true,
    .named = true,
  },
  [sym_json_array] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_coordinates] = {
    .visible = true,
    .named = true,
  },
  [sym_range] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_object_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_json_array_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_key = 2,
  field_name = 3,
  field_run = 4,
  field_value = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_key] = "key",
  [field_name] = "name",
  [field_run] = "run",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 3},
  [6] = {.index = 9, .length = 2},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_run, 1},
  [3] =
    {field_argument, 0},
  [4] =
    {field_argument, 1, .inherited = true},
    {field_name, 0},
  [6] =
    {field_argument, 1, .inherited = true},
    {field_name, 0},
    {field_run, 2},
  [9] =
    {field_argument, 0, .inherited = true},
    {field_argument, 1, .inherited = true},
  [11] =
    {field_key, 0},
    {field_value, 2},
  [13] =
    {field_key, 0},
    {field_value, 2},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 33,
  [35] = 8,
  [36] = 9,
  [37] = 23,
  [38] = 7,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 41,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 10,
  [53] = 11,
  [54] = 14,
  [55] = 15,
  [56] = 56,
  [57] = 17,
  [58] = 18,
  [59] = 21,
  [60] = 22,
  [61] = 40,
  [62] = 62,
  [63] = 49,
  [64] = 64,
  [65] = 62,
  [66] = 42,
  [67] = 64,
  [68] = 16,
  [69] = 69,
  [70] = 13,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 20,
  [76] = 26,
  [77] = 24,
  [78] = 19,
  [79] = 79,
  [80] = 25,
  [81] = 81,
  [82] = 82,
  [83] = 73,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 85,
  [89] = 89,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '!', 40,
        '"', 6,
        '#', 10,
        ',', 37,
        '.', 8,
        ':', 43,
        '=', 39,
        '@', 34,
        '[', 36,
        ']', 38,
        '{', 41,
        '}', 42,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
        '*', 30,
        '/', 30,
        '<', 30,
        '>', 30,
        'a', 35,
        'e', 35,
        'n', 35,
        'p', 35,
        'r', 35,
        's', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        0, 20,
        '\n', 20,
        '"', 6,
        '#', 14,
        '.', 8,
        '@', 34,
        '[', 36,
        'r', 24,
        '{', 41,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '!', 40,
        '"', 6,
        '#', 14,
        '.', 8,
        '@', 34,
        '[', 36,
        '{', 41,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
      );
      if (lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 6,
        '#', 14,
        '.', 8,
        '@', 34,
        '[', 36,
        'r', 24,
        '{', 41,
        '+', 31,
        '-', 31,
        '^', 48,
        '~', 48,
      );
      if (lookahead == '*' ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '>')) ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '"', 6,
        '#', 14,
        '.', 12,
        '[', 36,
        ']', 38,
        '{', 41,
        '+', 9,
        '-', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead == '}') ADVANCE(42);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(18);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 14:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '=') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(16);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_comments_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_comments_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_command_token1);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_run);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_command_name);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'n') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == ':') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '/') ADVANCE(29);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_bare_word_token1);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_resource_location);
      if (lookahead == ':') ADVANCE(15);
      if (('/' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_resource_location);
      if (('/' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_operators);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_operators);
      if (lookahead == '.') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(32);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_selector_token1);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_json_key_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_coordinates_token1);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 16},
  [32] = {.lex_state = 16},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 16},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 16},
  [47] = {.lex_state = 16},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 16},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 16},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 16},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 16},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 16},
  [84] = {.lex_state = 16},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_comments_token1] = ACTIONS(1),
    [sym_operators] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_selector_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_coordinates_token1] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(87),
    [sym_comments] = STATE(32),
    [sym_command] = STATE(32),
    [aux_sym_source_file_repeat1] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_comments_token1] = ACTIONS(5),
    [sym_command_name] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(9), 1,
      aux_sym_command_token1,
    ACTIONS(11), 1,
      sym_run,
    ACTIONS(13), 1,
      aux_sym_bare_word_token1,
    ACTIONS(19), 1,
      anon_sym_AT,
    ACTIONS(22), 1,
      anon_sym_LBRACK,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(28), 1,
      aux_sym_number_token1,
    ACTIONS(31), 1,
      aux_sym_coordinates_token1,
    ACTIONS(34), 1,
      anon_sym_DOT_DOT,
    STATE(2), 1,
      aux_sym_command_repeat1,
    STATE(10), 1,
      sym_number,
    STATE(12), 1,
      sym_argument,
    ACTIONS(16), 3,
      sym_resource_location,
      sym_operators,
      sym_string,
    STATE(25), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [50] = 14,
    ACTIONS(37), 1,
      aux_sym_command_token1,
    ACTIONS(39), 1,
      sym_run,
    ACTIONS(41), 1,
      aux_sym_bare_word_token1,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      aux_sym_number_token1,
    ACTIONS(53), 1,
      aux_sym_coordinates_token1,
    ACTIONS(55), 1,
      anon_sym_DOT_DOT,
    STATE(4), 1,
      aux_sym_command_repeat1,
    STATE(10), 1,
      sym_number,
    STATE(12), 1,
      sym_argument,
    ACTIONS(43), 3,
      sym_resource_location,
      sym_operators,
      sym_string,
    STATE(25), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [100] = 14,
    ACTIONS(41), 1,
      aux_sym_bare_word_token1,
    ACTIONS(45), 1,
      anon_sym_AT,
    ACTIONS(47), 1,
      anon_sym_LBRACK,
    ACTIONS(49), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      aux_sym_number_token1,
    ACTIONS(53), 1,
      aux_sym_coordinates_token1,
    ACTIONS(55), 1,
      anon_sym_DOT_DOT,
    ACTIONS(57), 1,
      aux_sym_command_token1,
    ACTIONS(59), 1,
      sym_run,
    STATE(2), 1,
      aux_sym_command_repeat1,
    STATE(10), 1,
      sym_number,
    STATE(12), 1,
      sym_argument,
    ACTIONS(43), 3,
      sym_resource_location,
      sym_operators,
      sym_string,
    STATE(25), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [150] = 13,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(65), 1,
      sym_string,
    ACTIONS(67), 1,
      anon_sym_AT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(71), 1,
      anon_sym_BANG,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(77), 1,
      aux_sym_coordinates_token1,
    ACTIONS(79), 1,
      anon_sym_DOT_DOT,
    STATE(52), 1,
      sym_number,
    STATE(69), 1,
      sym_argument,
    ACTIONS(63), 2,
      sym_resource_location,
      sym_operators,
    STATE(80), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [196] = 12,
    ACTIONS(61), 1,
      aux_sym_bare_word_token1,
    ACTIONS(65), 1,
      sym_string,
    ACTIONS(67), 1,
      anon_sym_AT,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(77), 1,
      aux_sym_coordinates_token1,
    ACTIONS(79), 1,
      anon_sym_DOT_DOT,
    STATE(52), 1,
      sym_number,
    STATE(71), 1,
      sym_argument,
    ACTIONS(63), 2,
      sym_resource_location,
      sym_operators,
    STATE(80), 6,
      sym_bare_word,
      sym_selector,
      sym_json_object,
      sym_json_array,
      sym_coordinates,
      sym_range,
  [239] = 4,
    ACTIONS(51), 1,
      aux_sym_number_token1,
    ACTIONS(81), 1,
      aux_sym_command_token1,
    STATE(13), 1,
      sym_number,
    ACTIONS(83), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [261] = 4,
    ACTIONS(51), 1,
      aux_sym_number_token1,
    ACTIONS(85), 1,
      aux_sym_command_token1,
    STATE(16), 1,
      sym_number,
    ACTIONS(87), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [283] = 4,
    ACTIONS(51), 1,
      aux_sym_number_token1,
    ACTIONS(89), 1,
      aux_sym_command_token1,
    STATE(20), 1,
      sym_number,
    ACTIONS(91), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [305] = 3,
    ACTIONS(93), 1,
      aux_sym_command_token1,
    ACTIONS(97), 1,
      anon_sym_DOT_DOT,
    ACTIONS(95), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
  [324] = 3,
    ACTIONS(99), 1,
      aux_sym_command_token1,
    ACTIONS(103), 1,
      anon_sym_LBRACK,
    ACTIONS(101), 10,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [343] = 2,
    ACTIONS(105), 1,
      aux_sym_command_token1,
    ACTIONS(107), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [360] = 2,
    ACTIONS(109), 1,
      aux_sym_command_token1,
    ACTIONS(111), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [377] = 2,
    ACTIONS(113), 1,
      aux_sym_command_token1,
    ACTIONS(115), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [394] = 2,
    ACTIONS(117), 1,
      aux_sym_command_token1,
    ACTIONS(119), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [411] = 2,
    ACTIONS(89), 1,
      aux_sym_command_token1,
    ACTIONS(91), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [428] = 2,
    ACTIONS(121), 1,
      aux_sym_command_token1,
    ACTIONS(123), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [445] = 2,
    ACTIONS(125), 1,
      aux_sym_command_token1,
    ACTIONS(127), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [462] = 2,
    ACTIONS(129), 1,
      aux_sym_command_token1,
    ACTIONS(131), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [479] = 2,
    ACTIONS(133), 1,
      aux_sym_command_token1,
    ACTIONS(135), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [496] = 2,
    ACTIONS(137), 1,
      aux_sym_command_token1,
    ACTIONS(139), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [513] = 2,
    ACTIONS(141), 1,
      aux_sym_command_token1,
    ACTIONS(143), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [530] = 2,
    ACTIONS(145), 1,
      aux_sym_command_token1,
    ACTIONS(147), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [547] = 2,
    ACTIONS(149), 1,
      aux_sym_command_token1,
    ACTIONS(151), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [564] = 2,
    ACTIONS(93), 1,
      aux_sym_command_token1,
    ACTIONS(95), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [581] = 2,
    ACTIONS(153), 1,
      aux_sym_command_token1,
    ACTIONS(155), 11,
      sym_run,
      aux_sym_bare_word_token1,
      sym_resource_location,
      sym_operators,
      sym_string,
      anon_sym_AT,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      aux_sym_number_token1,
      aux_sym_coordinates_token1,
      anon_sym_DOT_DOT,
  [598] = 6,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(159), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 2,
      sym_resource_location,
      sym_string,
    STATE(49), 3,
      sym_json_object,
      sym_json_array,
      sym_number,
  [620] = 6,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(163), 1,
      anon_sym_RBRACK,
    ACTIONS(161), 2,
      sym_resource_location,
      sym_string,
    STATE(63), 3,
      sym_json_object,
      sym_json_array,
      sym_number,
  [642] = 5,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(165), 2,
      sym_resource_location,
      sym_string,
    STATE(81), 3,
      sym_json_object,
      sym_json_array,
      sym_number,
  [661] = 5,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    ACTIONS(167), 2,
      sym_resource_location,
      sym_string,
    STATE(82), 3,
      sym_json_object,
      sym_json_array,
      sym_number,
  [680] = 4,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 1,
      aux_sym_comments_token1,
    ACTIONS(174), 1,
      sym_command_name,
    STATE(31), 3,
      sym_comments,
      sym_command,
      aux_sym_source_file_repeat1,
  [695] = 4,
    ACTIONS(5), 1,
      aux_sym_comments_token1,
    ACTIONS(7), 1,
      sym_command_name,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
    STATE(31), 3,
      sym_comments,
      sym_command,
      aux_sym_source_file_repeat1,
  [710] = 4,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_json_pair,
    STATE(86), 1,
      sym_json_key,
    ACTIONS(179), 2,
      sym_string,
      aux_sym_json_key_token1,
  [724] = 4,
    ACTIONS(183), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      sym_json_pair,
    STATE(86), 1,
      sym_json_key,
    ACTIONS(179), 2,
      sym_string,
      aux_sym_json_key_token1,
  [738] = 3,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    STATE(68), 1,
      sym_number,
    ACTIONS(85), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [749] = 3,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    STATE(75), 1,
      sym_number,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [760] = 1,
    ACTIONS(145), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_DOT_DOT,
  [767] = 3,
    ACTIONS(75), 1,
      aux_sym_number_token1,
    STATE(70), 1,
      sym_number,
    ACTIONS(81), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [778] = 3,
    STATE(74), 1,
      sym_json_pair,
    STATE(86), 1,
      sym_json_key,
    ACTIONS(179), 2,
      sym_string,
      aux_sym_json_key_token1,
  [789] = 3,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_json_object_repeat1,
  [799] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_selector_repeat1,
  [809] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RBRACK,
    STATE(48), 1,
      aux_sym_selector_repeat1,
  [819] = 1,
    ACTIONS(195), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [825] = 3,
    ACTIONS(197), 1,
      anon_sym_COMMA,
    ACTIONS(200), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_json_array_repeat1,
  [835] = 3,
    ACTIONS(202), 1,
      anon_sym_COMMA,
    ACTIONS(205), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_json_object_repeat1,
  [845] = 1,
    ACTIONS(207), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [851] = 1,
    ACTIONS(209), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [857] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_selector_repeat1,
  [867] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(67), 1,
      aux_sym_json_array_repeat1,
  [877] = 3,
    ACTIONS(217), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_selector_repeat1,
  [887] = 1,
    ACTIONS(222), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [893] = 2,
    ACTIONS(224), 1,
      anon_sym_DOT_DOT,
    ACTIONS(93), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [901] = 2,
    ACTIONS(226), 1,
      anon_sym_LBRACK,
    ACTIONS(99), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [909] = 1,
    ACTIONS(113), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [915] = 1,
    ACTIONS(117), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [921] = 1,
    ACTIONS(228), 3,
      ts_builtin_sym_end,
      aux_sym_comments_token1,
      sym_command_name,
  [927] = 1,
    ACTIONS(121), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [933] = 1,
    ACTIONS(125), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [939] = 1,
    ACTIONS(137), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [945] = 1,
    ACTIONS(141), 3,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [951] = 3,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_json_object_repeat1,
  [961] = 3,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_json_object_repeat1,
  [971] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
    STATE(64), 1,
      aux_sym_json_array_repeat1,
  [981] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(236), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_json_array_repeat1,
  [991] = 3,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_RBRACE,
    STATE(45), 1,
      aux_sym_json_object_repeat1,
  [1001] = 3,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(240), 1,
      anon_sym_RBRACK,
    STATE(41), 1,
      aux_sym_selector_repeat1,
  [1011] = 3,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(242), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      aux_sym_json_array_repeat1,
  [1021] = 1,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1026] = 1,
    ACTIONS(244), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1031] = 1,
    ACTIONS(109), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1036] = 1,
    ACTIONS(246), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1041] = 1,
    ACTIONS(220), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1046] = 2,
    ACTIONS(248), 1,
      sym_command_name,
    STATE(42), 1,
      sym_selector_argument,
  [1053] = 1,
    ACTIONS(205), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1058] = 1,
    ACTIONS(133), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1063] = 1,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1068] = 1,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1073] = 1,
    ACTIONS(129), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1078] = 2,
    ACTIONS(248), 1,
      sym_command_name,
    STATE(72), 1,
      sym_selector_argument,
  [1085] = 1,
    ACTIONS(93), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1090] = 1,
    ACTIONS(200), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1095] = 1,
    ACTIONS(250), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1100] = 2,
    ACTIONS(248), 1,
      sym_command_name,
    STATE(66), 1,
      sym_selector_argument,
  [1107] = 1,
    ACTIONS(252), 1,
      anon_sym_EQ,
  [1111] = 1,
    ACTIONS(254), 1,
      aux_sym_selector_token1,
  [1115] = 1,
    ACTIONS(256), 1,
      anon_sym_COLON,
  [1119] = 1,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
  [1123] = 1,
    ACTIONS(260), 1,
      aux_sym_selector_token1,
  [1127] = 1,
    ACTIONS(262), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 239,
  [SMALL_STATE(8)] = 261,
  [SMALL_STATE(9)] = 283,
  [SMALL_STATE(10)] = 305,
  [SMALL_STATE(11)] = 324,
  [SMALL_STATE(12)] = 343,
  [SMALL_STATE(13)] = 360,
  [SMALL_STATE(14)] = 377,
  [SMALL_STATE(15)] = 394,
  [SMALL_STATE(16)] = 411,
  [SMALL_STATE(17)] = 428,
  [SMALL_STATE(18)] = 445,
  [SMALL_STATE(19)] = 462,
  [SMALL_STATE(20)] = 479,
  [SMALL_STATE(21)] = 496,
  [SMALL_STATE(22)] = 513,
  [SMALL_STATE(23)] = 530,
  [SMALL_STATE(24)] = 547,
  [SMALL_STATE(25)] = 564,
  [SMALL_STATE(26)] = 581,
  [SMALL_STATE(27)] = 598,
  [SMALL_STATE(28)] = 620,
  [SMALL_STATE(29)] = 642,
  [SMALL_STATE(30)] = 661,
  [SMALL_STATE(31)] = 680,
  [SMALL_STATE(32)] = 695,
  [SMALL_STATE(33)] = 710,
  [SMALL_STATE(34)] = 724,
  [SMALL_STATE(35)] = 738,
  [SMALL_STATE(36)] = 749,
  [SMALL_STATE(37)] = 760,
  [SMALL_STATE(38)] = 767,
  [SMALL_STATE(39)] = 778,
  [SMALL_STATE(40)] = 789,
  [SMALL_STATE(41)] = 799,
  [SMALL_STATE(42)] = 809,
  [SMALL_STATE(43)] = 819,
  [SMALL_STATE(44)] = 825,
  [SMALL_STATE(45)] = 835,
  [SMALL_STATE(46)] = 845,
  [SMALL_STATE(47)] = 851,
  [SMALL_STATE(48)] = 857,
  [SMALL_STATE(49)] = 867,
  [SMALL_STATE(50)] = 877,
  [SMALL_STATE(51)] = 887,
  [SMALL_STATE(52)] = 893,
  [SMALL_STATE(53)] = 901,
  [SMALL_STATE(54)] = 909,
  [SMALL_STATE(55)] = 915,
  [SMALL_STATE(56)] = 921,
  [SMALL_STATE(57)] = 927,
  [SMALL_STATE(58)] = 933,
  [SMALL_STATE(59)] = 939,
  [SMALL_STATE(60)] = 945,
  [SMALL_STATE(61)] = 951,
  [SMALL_STATE(62)] = 961,
  [SMALL_STATE(63)] = 971,
  [SMALL_STATE(64)] = 981,
  [SMALL_STATE(65)] = 991,
  [SMALL_STATE(66)] = 1001,
  [SMALL_STATE(67)] = 1011,
  [SMALL_STATE(68)] = 1021,
  [SMALL_STATE(69)] = 1026,
  [SMALL_STATE(70)] = 1031,
  [SMALL_STATE(71)] = 1036,
  [SMALL_STATE(72)] = 1041,
  [SMALL_STATE(73)] = 1046,
  [SMALL_STATE(74)] = 1053,
  [SMALL_STATE(75)] = 1058,
  [SMALL_STATE(76)] = 1063,
  [SMALL_STATE(77)] = 1068,
  [SMALL_STATE(78)] = 1073,
  [SMALL_STATE(79)] = 1078,
  [SMALL_STATE(80)] = 1085,
  [SMALL_STATE(81)] = 1090,
  [SMALL_STATE(82)] = 1095,
  [SMALL_STATE(83)] = 1100,
  [SMALL_STATE(84)] = 1107,
  [SMALL_STATE(85)] = 1111,
  [SMALL_STATE(86)] = 1115,
  [SMALL_STATE(87)] = 1119,
  [SMALL_STATE(88)] = 1123,
  [SMALL_STATE(89)] = 1127,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(26),
  [16] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(25),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(88),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(27),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(33),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(23),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2, 0, 6), SHIFT_REPEAT(8),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coordinates, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_coordinates, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 2, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1, 0, 3),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1, 0, 3),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_coordinates, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_coordinates, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 2, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 6, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 6, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_range, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_array, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_array, 4, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_object, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_json_object, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 5, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 5, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bare_word, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bare_word, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comments, 1, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_array_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_json_object_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 4),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 5),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selector_repeat1, 2, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 2),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_argument, 3, 0, 7),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector_argument, 4, 0, 8),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_pair, 3, 0, 7),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [258] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_json_key, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mcfunction(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "mcfunction",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
